runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /(.+\.php)$
  script: \1
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always

skip_files:
# App Engine default patterns.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

beta_settings:
  cloud_sql_instances: uopvisitorapp:europe-west1:visitorapp

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/uopvisitorapp:europe-west1:visitorapp;dbname=visitorapp
  MYSQL_USER: root
  MYSQL_PASSWORD: ''

